// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD60xC_UpQbjnT2z1rwJO8uWur56LILsHY',
    appId: '1:480869520638:web:bfc0e4394bef2095a6c1af',
    messagingSenderId: '480869520638',
    projectId: 'crm-medical-1a51f',
    authDomain: 'crm-medical-1a51f.firebaseapp.com',
    storageBucket: 'crm-medical-1a51f.firebasestorage.app',
    measurementId: 'G-GX7N4WXBZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPWZyvGrzVVQo56_0-FVZuJuBJZauS2KI',
    appId: '1:480869520638:android:60cb89fc1eba676aa6c1af',
    messagingSenderId: '480869520638',
    projectId: 'crm-medical-1a51f',
    storageBucket: 'crm-medical-1a51f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-6Q3nhN_Rlc7DYFJwRXoRa23eu54aE8A',
    appId: '1:480869520638:ios:f204e7fdd6bb755aa6c1af',
    messagingSenderId: '480869520638',
    projectId: 'crm-medical-1a51f',
    storageBucket: 'crm-medical-1a51f.firebasestorage.app',
    iosBundleId: 'com.example.appExamen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-6Q3nhN_Rlc7DYFJwRXoRa23eu54aE8A',
    appId: '1:480869520638:ios:f204e7fdd6bb755aa6c1af',
    messagingSenderId: '480869520638',
    projectId: 'crm-medical-1a51f',
    storageBucket: 'crm-medical-1a51f.firebasestorage.app',
    iosBundleId: 'com.example.appExamen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD60xC_UpQbjnT2z1rwJO8uWur56LILsHY',
    appId: '1:480869520638:web:9ac870dd71f0a5c0a6c1af',
    messagingSenderId: '480869520638',
    projectId: 'crm-medical-1a51f',
    authDomain: 'crm-medical-1a51f.firebaseapp.com',
    storageBucket: 'crm-medical-1a51f.firebasestorage.app',
    measurementId: 'G-R7Q214HM3M',
  );
}
